### ISSUE TITLE
> But I also confirmed on another system that there's a problem with the PyQt bits

### ISSUE THREAD

**Issue by thorstenwagner** [MPI-Dortmund/napari-tomotwin#10]
> But I also confirmed on another system that there's a problem with the PyQt bits
> 
> label_layer.visible = 1 AttributeError: 'NoneType' object has no attribute 'visible'

When does that happen? I need to reproduce it to fix it.

_Originally posted by @thorstenwagner in https://github.com/MPI-Dortmund/tomotwin-cryoet/discussions/15#discussioncomment-6701019_

**Comment by 3P1L** [comment]
Hi Thorsten!

So here is how I can reproduce the problem:

1) On My Mac

• Start Napari
• Load Tomogram (File > Open)
• Load UMAP (Plugins > napari-tomotwin > Cluster -> Select File -> load)

Note: No UMAP projection is displayed! (screenshot)

• click anywhere on the tomogram

> Error log attached.

![Napari_MAC_1](https://github.com/MPI-Dortmund/napari-tomotwin/assets/48826527/47c9be65-0315-44c6-98d3-1c413c5ea418)
[Napari_MAC.txt](https://github.com/MPI-Dortmund/napari-tomotwin/files/12332971/Napari_MAC.txt)

**Comment by 3P1L** [comment]
Without loading the mask, the effect is the same on my linux system.

However, when I add the mask (.mrci) and then load the .tumap everything is OK.

![Napari_Linux_1](https://github.com/MPI-Dortmund/napari-tomotwin/assets/48826527/cad7ddb8-57c9-4708-9d57-437f3c1633ec)

**Comment by thorstenwagner** [comment]
Will look into it, sorry that it take so long
