### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by goanpeca** [MPI-Dortmund/napari-tomotwin#13]
Hi team!

While working on https://github.com/conda-forge/napari-tomotwin-feedstock/pull/7, we found that  `magicgui` is directly imported by the code (see https://github.com/search?q=repo%3AMPI-Dortmund%2Fnapari-tomotwin%20magicgui&type=code) but it is not currently being declared as a requirement.

Could you please fix this for the next release?

Cheers 🚀

**Comment by thorstenwagner** [comment]
Thanks! Will be fixed with the next release.
